version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: adminpass
      POSTGRES_USER: admin
      POSTGRES_DB: broker
    ports:
      - "5432:5432"

  broker:
    build:
      context: .
    environment:
      POSTGRES_URI: postgres://admin:adminpass@postgres:5432/broker?sslmode=disable
      SERVER_PORT: 8080
    depends_on:
      - postgres
    ports:
      - "8080:8080"
